version: "3.8"
services:
    #php server
    php:
        container_name: php
        build:
            context: .
            target: php

        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8080
        depends_on:
            - database
        environment:
            - XDEBUG_CONFIG=mode=debug client_host=host.docker.internal idekey=phpstorm start_with_request=trigger remote_handler=dbgp client_port=9003
    #database services
    database:
        container_name: database
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=geno
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=test
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data: ~
