<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Challenge>
 */
class ChallengeFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => $this->faker->word,
            'description' => $this->faker->sentence,
            'active' => $this->faker->boolean(80), // Adjust the probability as needed
            'round_id' => function () {
                // Get a random round ID from the rounds table
                return \App\Models\Round::inRandomOrder()->first()->id;
            },
            'created_at' => null, // Automatically generated by Laravel
            'updated_at' => null, // Automatically generated by Laravel
        ];
    }
}
